# Generated by Django 4.1.4 on 2022-12-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='balance',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='bank',
            field=models.CharField(choices=[('INDIAN BANK', 'INDIAN BANK'), ('STATE BANK OF INDIA', 'STATE BANK OF INDIA'), ('YES BANK', 'YES BANK'), ('INDIAN OVERSEAS BANK', 'INDIAN OVERSEAS BANK')], max_length=50),
        ),
    ]
