# Generated by Django 4.1.4 on 2023-01-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_atm_balance_alter_atm_bank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='atm',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='card',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
